In [2]:
# !pip install autokeras


In [3]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist

import autokeras as ak


## A Simple Example
The first step is to prepare your data. Here we use the MNIST dataset as an example


In [9]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)  # (60000, 28, 28)
print(y_train.shape)  # (60000,)
print(y_train[:3])  # array([7, 2, 1], dtype=uint8)

(60000, 28, 28)
(60000,)
[5 0 4]


The second step is to run the ImageClassifier.
It is recommended have more trials for more complicated datasets.
This is just a quick demo of MNIST, so we set max_trials to 1.
For the same reason, we set epochs to 10.
You can also leave the epochs unspecified for an adaptive number of epochs.


In [10]:
# Initialize the image classifier.
clf = ak.ImageClassifier(overwrite=True, max_trials=1)
# Feed the image classifier with training data.
clf.fit(x_train, y_train, epochs=10)


# Predict with the best model.
predicted_y = clf.predict(x_test)
print(predicted_y)


# Evaluate the best model with testing data.
print(clf.evaluate(x_test, y_test))


Trial 1 Complete [00h 01m 40s]
val_loss: 0.04037860780954361

Best val_loss So Far: 0.04037860780954361
Total elapsed time: 00h 01m 40s
Epoch 1/10
1875/1875 [==============================] - 9s 4ms/step - loss: 0.1630 - accuracy: 0.9515
Epoch 2/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0743 - accuracy: 0.9765
Epoch 3/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0596 - accuracy: 0.9816
Epoch 4/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0509 - accuracy: 0.9837
Epoch 5/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0430 - accuracy: 0.9863
Epoch 6/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0391 - accuracy: 0.9880
Epoch 7/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0365 - accuracy: 0.9881
Epoch 8/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0339 - accuracy: 0.9887
Epoch 9/10
1875/1875 [==========================

313/313 [==============================] - 1s 2ms/step
[['7']
 ['2']
 ['1']
 ...
 ['4']
 ['5']
 ['6']]
313/313 [==============================] - 1s 3ms/step - loss: 0.0344 - accuracy: 0.9889
[0.03440522775053978, 0.9889000058174133]


In [11]:
print(clf)

## Validation Data
By default, AutoKeras use the last 20% of training data as validation data. As
shown in the example below, you can use validation_split to specify the
percentage.


In [12]:
clf.fit(
    x_train,
    y_train,
    # Split the training data and use the last 15% as validation data.
    validation_split=0.15,
    epochs=10,
)


In [13]:
# Predict with the best model.
predicted_y = clf.predict(x_test)
print(predicted_y)


# Evaluate the best model with testing data.
print(clf.evaluate(x_test, y_test))

313/313 [==============================] - 1s 2ms/step
[['7']
 ['2']
 ['1']
 ...
 ['4']
 ['5']
 ['6']]
313/313 [==============================] - 1s 3ms/step - loss: 0.0344 - accuracy: 0.9889
[0.03440522775053978, 0.9889000058174133]


You can also use your own validation set instead of splitting it from the
training data with validation_data.


In [14]:
split = 50000
x_val = x_train[split:]
y_val = y_train[split:]
x_train = x_train[:split]
y_train = y_train[:split]
clf.fit(
    x_train,
    y_train,
    # Use your own validation set.
    validation_data=(x_val, y_val),
    epochs=10,
)


In [15]:
# Predict with the best model.
predicted_y = clf.predict(x_test)
print(predicted_y)


# Evaluate the best model with testing data.
print(clf.evaluate(x_test, y_test))

313/313 [==============================] - 1s 2ms/step
[['7']
 ['2']
 ['1']
 ...
 ['4']
 ['5']
 ['6']]
313/313 [==============================] - 1s 3ms/step - loss: 0.0344 - accuracy: 0.9889
[0.03440522775053978, 0.9889000058174133]


## Customized Search Space
For advanced users, you may customize your search space by using AutoModel
instead of ImageClassifier. You can configure the ImageBlock for some
high-level configurations, e.g., block_type for the type of neural network to
search, normalize for whether to do data normalization, augment for whether to
do data augmentation. You can also do not specify these arguments, which would
leave the different choices to be tuned automatically. See the following
example for detail.


In [16]:
input_node = ak.ImageInput()
output_node = ak.ImageBlock(
    # Only search ResNet architectures.
    block_type="resnet",
    # Normalize the dataset.
    normalize=True,
    # Do not do data augmentation.
    augment=False,
)(input_node)
output_node = ak.ClassificationHead()(output_node)
clf = ak.AutoModel(
    inputs=input_node, outputs=output_node, overwrite=True, max_trials=1
)
clf.fit(x_train, y_train, epochs=10)


Trial 1 Complete [00h 11m 31s]
val_loss: 0.08786610513925552

Best val_loss So Far: 0.08786610513925552
Total elapsed time: 00h 11m 31s
Epoch 1/10
1563/1563 [==============================] - 67s 39ms/step - loss: 0.4309 - accuracy: 0.9035
Epoch 2/10
1563/1563 [==============================] - 61s 39ms/step - loss: 0.3203 - accuracy: 0.9326
Epoch 3/10
1563/1563 [==============================] - 61s 39ms/step - loss: 0.3199 - accuracy: 0.9284
Epoch 4/10
1563/1563 [==============================] - 61s 39ms/step - loss: 0.1962 - accuracy: 0.9571
Epoch 5/10
1563/1563 [==============================] - 60s 38ms/step - loss: 0.2597 - accuracy: 0.9422
Epoch 6/10
1563/1563 [==============================] - 60s 39ms/step - loss: 0.1249 - accuracy: 0.9694
Epoch 7/10
1563/1563 [==============================] - 62s 39ms/step - loss: 0.1022 - accuracy: 0.9765
Epoch 8/10
1563/1563 [==============================] - 61s 39ms/step - loss: 0.1041 - accuracy: 0.9746
Epoch 9/10
1563/1563 [==========

The usage of AutoModel is similar to the functional API of Keras. Basically, you are
building a graph, whose edges are blocks and the nodes are intermediate outputs of
blocks. To add an edge from input_node to output_node with output_node =
ak.[some_block]([block_args])(input_node).

You can even also use more fine grained blocks to customize the search space even
further. See the following example.


In [17]:
input_node = ak.ImageInput()
output_node = ak.Normalization()(input_node)
output_node = ak.ImageAugmentation(horizontal_flip=False)(output_node)
output_node = ak.ResNetBlock(version="v2")(output_node)
output_node = ak.ClassificationHead()(output_node)
clf = ak.AutoModel(
    inputs=input_node, outputs=output_node, overwrite=True, max_trials=1
)
clf.fit(x_train, y_train, epochs=10)


Trial 1 Complete [00h 33m 08s]
val_loss: 0.6943337917327881

Best val_loss So Far: 0.6943337917327881
Total elapsed time: 00h 33m 08s


Epoch 1/10


1563/1563 [==============================] - 241s 150ms/step - loss: 0.3432 - accuracy: 0.9002
Epoch 2/10
1563/1563 [==============================] - 235s 151ms/step - loss: 0.1663 - accuracy: 0.9531
Epoch 3/10
1563/1563 [==============================] - 233s 149ms/step - loss: 0.1383 - accuracy: 0.9616
Epoch 4/10
1563/1563 [==============================] - 233s 149ms/step - loss: 0.1272 - accuracy: 0.9651
Epoch 5/10
1563/1563 [==============================] - 233s 149ms/step - loss: 0.1049 - accuracy: 0.9699
Epoch 6/10
1563/1563 [==============================] - 234s 149ms/step - loss: 0.0991 - accuracy: 0.9722
Epoch 7/10
1563/1563 [==============================] - 233s 149ms/step - loss: 0.1038 - accuracy: 0.9709
Epoch 8/10
1563/1563 [==============================] - 232s 149ms/step - loss: 0.0673 - accuracy: 0.9802
Epoch 9/10
1563/1563 [==============================] - 232s 148ms/step - loss: 0.0583 - accuracy: 0.9827
Epoch 10/10
1563/1563 [==============================] - 

## Data Format
The AutoKeras ImageClassifier is quite flexible for the data format.

For the image, it accepts data formats both with and without the channel
dimension. The images in the MNIST dataset do not have the channel dimension.
Each image is a matrix with shape (28, 28). AutoKeras also accepts images of
three dimensions with the channel dimension at last, e.g., (32, 32, 3), (28,
28, 1).

For the classification labels, AutoKeras accepts both plain labels, i.e.
strings or integers, and one-hot encoded encoded labels, i.e. vectors of 0s and
1s.

So if you prepare your data in the following way, the ImageClassifier should
still work.


In [18]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Reshape the images to have the channel dimension.
x_train = x_train.reshape(x_train.shape + (1,))
x_test = x_test.reshape(x_test.shape + (1,))

# One-hot encode the labels.
eye = np.eye(10)
y_train = eye[y_train]
y_test = eye[y_test]

print(x_train.shape)  # (60000, 28, 28, 1)
print(y_train.shape)  # (60000, 10)
print(y_train[:3])
# array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])


(60000, 28, 28, 1)
(60000, 10)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


We also support using tf.data.Dataset format for the training data.


In [19]:
train_set = tf.data.Dataset.from_tensor_slices(((x_train,), (y_train,)))
test_set = tf.data.Dataset.from_tensor_slices(((x_test,), (y_test,)))

clf = ak.ImageClassifier(overwrite=True, max_trials=1)
# Feed the tensorflow Dataset to the classifier.
clf.fit(train_set, epochs=10)
# Predict with the best model.
predicted_y = clf.predict(test_set)
# Evaluate the best model with testing data.
print(clf.evaluate(test_set))


Trial 1 Complete [00h 01m 40s]
val_loss: 0.035456299781799316

Best val_loss So Far: 0.035456299781799316
Total elapsed time: 00h 01m 40s
Epoch 1/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1615 - accuracy: 0.9506
Epoch 2/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0743 - accuracy: 0.9777
Epoch 3/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0610 - accuracy: 0.9815
Epoch 4/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0525 - accuracy: 0.9839
Epoch 5/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0461 - accuracy: 0.9854
Epoch 6/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0407 - accuracy: 0.9871
Epoch 7/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0378 - accuracy: 0.9877
Epoch 8/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0331 - accuracy: 0.9886
Epoch 9/10
1875/1875 [=====================

313/313 [==============================] - 1s 4ms/step - loss: 0.0279 - accuracy: 0.9904
[0.027931582182645798, 0.9904000163078308]
